name: Windows
on: push

jobs:
  buildWin:
    runs-on: windows-latest
    steps:
    
    - name: checkout sources
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        modules: 'imageformats'
        arch: 'win64_mingw81'
        aqtversion: '==1.1.6'
        extra: '--external 7z'
        
    - name: Build AnimeEffects
      shell: cmd
      run: |
        qmake src\AnimeEffects.pro
        make
        dir
        echo $QT_DIR
        mkdir .\AnimeEffects-Windows
        windeployqt --dir .\AnimeEffects-Windows .\release\AnimeEffects.exe
        copy /Y .\release\AnimeEffects.exe .\AnimeEffects-Windows\AnimeEffects.exe
        tar.exe -a -c -f AnimeEffects-Windows.zip .\AnimeEffects-Windows
        
    - name: GitHub Releases
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: AnimeEffects-Windows.zip
        tag: ${{ github.ref }}
    
