name: Windows Latest
on: 
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'
jobs:
  buildWin64:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.6.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtimageformats qtmultimedia qt5compat'
        tools: 'tools_cmake tools_ninja'
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@523828e49cd4afabce369c39c7ee6543a2b7a735
      with:
         vulkan-query-version: 1.3.204.0
         vulkan-components: Vulkan-Headers, Vulkan-Loader
         vulkan-use-cache: true
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
         arch: x64
    - name: Setup PATH
      run: |
          echo $env:Qt6_Dir\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $env:IQTA_TOOLS\win64_msvc2019_64\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Build AnimeEffects
      shell: powershell
      run: |
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release
        cd build/src/gui/Release
        mkdir .\AnimeEffects-Windows-x64
        windeployqt --dir .\AnimeEffects-Windows-x64 .\AnimeEffects.exe
        Copy-Item -Path "..\data" -Destination ".\AnimeEffects-Windows-x64\" -recurse -Force
        Copy-Item ".\AnimeEffects.exe" ".\AnimeEffects-Windows-x64\"
    - name: Github Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AnimeEffects-Windows-x64
        path: D:/a/AnimeEffects/AnimeEffects/build/src/gui/Release/AnimeEffects-Windows-x64/
