
name: Windows
on: workflow_dispatch

jobs:
  buildWin:
    runs-on: windows-latest
    steps:
    
    - name: checkout sources
      uses: actions/checkout@v3
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        
    - name: Build AnimeEffects
      shell: powershell
      run: |
        qmake src\AnimeEffects.pro
        mingw32-make -j8
        dir
        echo $QT_DIR
        mkdir .\AnimeEffects-Windows
        windeployqt --dir .\AnimeEffects-Windows .\release\AnimeEffects.exe
        Copy-Item -Path ".\data" -Destination ".\AnimeEffects-Windows\" -recurse -Force
        Copy-Item ".\AnimeEffects.exe" ".\AnimeEffects-Windows\"
        tar.exe -a -c -f AnimeEffects-Windows.zip .\AnimeEffects-Windows
        
    - name: Github Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AnimeEffects 
        path: AnimeEffects-Windows.zip
        
    - name: GitHub Releases
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: AnimeEffects-Windows.zip
        tag: ${{ github.ref }}
    
