name: Ubuntu 18.04
on: 
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
  buildOnBionic:
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:18.04 # yes, this looks redundant, but something is messed up with their Ubuntu image that causes our builds to fail

    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: add build dependencies
      run: |
        apt update
        apt install -y software-properties-common g++ make wget rsync
        add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic
        apt-get update
        apt install -y qt515base qt515x11extras qt515tools libgl1-mesa-dev qt515imageformats
        
    - name: build AnimeEffects
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        source /opt/qt*/bin/qt*-env.sh || true
        /opt/qt515/bin/qmake src/AnimeEffects.pro -r CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        mkdir -p appdir/usr/bin
        cp AnimeEffects appdir/usr/bin
        cp -R data appdir/usr/bin/data
        find appdir/
        export APPIMAGE_EXTRACT_AND_RUN=1
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        if [[ "$RELEASE_VERSION" != "" ]]; then export VERSION=$RELEASE_VERSION;fi
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage -verbose=2

    - name: Github Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AnimeEffects 
        path: |
          AnimeEffects-x86_64.AppImage
          /__w/AnimeEffects/AnimeEffects/appdir/AnimeEffects.desktop
